Assumptions:
A, B, C, D, E, F, P, X, Y: Point
cb, cc: Circle
90 == angle(A,F,B)
between(B, F, C)
between(A, P, F)
between(C, D, F)
between(B, E, F)
angle(A,C,F) == angle(P,D,F)
angle(A,B,F) == angle(P,E,F)
A, B, D, X in cb
distance(A,D) == distance(D,X)
A, C, E, Y in cc
distance(A,E) == distance(E,Y)
Embeds:
A := (0.0, 2.0)
B := (-1.0, 0.0)
C := (2.0, 0.0)
P := (0.0, 0.5)
F := (0.0, 0.0)
D := (0.5, 0.0)
E := (-0.25, 0.0)
X := (-1.4, 0.8)
Y := (1.75, -0.25)
cb := ((-0.25, 0.875), 1.1524430513381958)
cc := ((0.875, 0.875), 1.4252192974090576)
Need to prove:
concyclic(B, C, X, Y)
Proof:
By line_equality_v1 on B, E, D we get Line(B,E) == Line(D,E), Line(B,D) == Line(B,E)  # (A1, A3, A4) -> (0)
By line_equality_v1 on B, E, C we get Line(B,E) == Line(C,E), Line(B,C) == Line(B,E)  # (A1, A4) -> (1)
By angles_on_chord on A, D, B, X, cb we get angle(A,B,D) == angle(A,X,D) mod 180  # (A7) -> (2)
By angles_on_chord on D, X, A, B, cb we get angle(D,A,X) == angle(D,B,X) mod 180  # (A7) -> (3)
By congruent_triangles_v4 on A, D, X, X, D, A we get 0 == angle(A,X,D) + angle(X,A,D)  # (A8) -> (4)
By angles_on_chord on A, E, C, Y, cc we get angle(A,C,E) == angle(A,Y,E) mod 180  # (A9) -> (5)
By angles_on_chord on E, Y, A, C, cc we get angle(E,A,Y) == angle(E,C,Y) mod 180  # (A9) -> (6)
By congruent_triangles_v4 on A, E, Y, Y, E, A we get 0 == angle(A,Y,E) + angle(Y,A,E)  # (A10) -> (7)
Let A' := line_intersection(Line(B,X),Line(C,Y))
By line_equality_v3 on B, X, A' we get Line(B,X) == Line(B,A')  # (8) -> (9)
By line_equality_v3 on C, Y, A' we get Line(C,Y) == Line(C,A')  # (8) -> (10)
By congruent_triangles_v3 on B, C, A, B, C, A' we get distance(A,B) == distance(B,A')  # (0, 1, 2, 4, 5, 7, 9, 10) -> (11)
It is almost always true that orientation(A,F,B) != orientation(B,A',F)
By congruent_triangles_v5 on F, B, A, F, B, A' we get 0 == angle(A',F,B) + angle(A,F,B), triangle(B, F, A')  # (11, 12) -> (13)
By complementary_angles_180_v1 on B, A, F, A' we get collinear(A, F, A')  # (A0, 13) -> (14)
By similar_triangles_v0 on A, F, C, P, F, D we get distance(A,F) / distance(F,P) == distance(C,F) / distance(D,F)  # (A2, A3, A5) -> (15)   
By similar_triangles_v0 on A, F, B, P, F, E we get distance(A,F) / distance(F,P) == distance(B,F) / distance(E,F)  # (A2, A4, A6) -> (16)   
By intersection_on_radical on A, cb, cc we get A in radical_axis(cb,cc)  # (A7, A9) -> (17)
By inner_transitivity_of_between on B, F, D, C we get between(B, F, D)  # (A1, A3) -> (18)
By inner_transitivity_of_between on C, F, E, B we get between(C, F, E)  # (A1, A4) -> (19)
By equal_power_on_radical_v4 on F, D, B, E, C, cb, cc we get F in radical_axis(cb,cc)  # (A7, A9, 15, 16, 18, 19) -> (20)
By line_unique_points on A, F, Line(A,F), radical_axis(cb,cc) we get Line(A,F) == radical_axis(cb,cc)  # (17, 20) -> (21)
By radical_axis_weak on A', Y, C, X, B, cc, cb we get concyclic(B, C, X, Y)  # (14, 21) -> (22)